gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - default
    cherryPickedCommitBgColor:
      - default
      - underline
    cherryPickedCommitFgColor:
      - yellow
git:
  autoFetch: false
  branchLogCmd: git log --color=always --graph --format='%C(auto)%h%d %s %C(dim)<%an> %C(green)%cr' {{branchName}}
  allBranchesLogCmds:
    - git log --color=always --all --graph --format='%C(auto)%h%d %s %C(dim)<%an> %C(green)%cr'
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: DELTA_FEATURES=+lazygit delta --dark --paging=never
notARepository: quit
promptToReturnFromSubprocess: false
keybinding:
  commits:
    moveDownCommit: <c-d>
    moveUpCommit: <c-u>
